### global setting: from

### global setting: to

mrt-dump:
  - config:
      dump-type: updates
      file-name: /tmp/updates.2006-01-02_1504.mrt
      rotation-interval: 180

### rpki setting: from

### rpki setting: to

neighbors:
### neighbor 10.173.176.101 setting: from

### neighbor 10.173.176.101 setting: to
  - config:
      neighbor-address: 10.173.176.102
      peer-as: 65002
      auth-password: pass65002
      admin-down: false
    timers:
      config:
        hold-time: 90
        keepalive-interval: 30
    transport:
      config:
        passive-mode: true
    route-server:
      config:
        route-server-client: true
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast
        prefix-limit:
          config:
            max-prefixes: 2000
    apply-policy:
      config:
        default-import-policy: accept-route
        import-policy-list:
          - AS65002-IMPORT
        default-export-policy: accept-route
        export-policy-list:
          - AS65002-EXPORT
  - config:
      neighbor-address: 10.173.176.103
      peer-as: 65003
      auth-password: pass65003
      admin-down: false
    timers:
      config:
        hold-time: 90
        keepalive-interval: 30
    transport:
      config:
        passive-mode: true
    route-server:
      config:
        route-server-client: true
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast
        prefix-limit:
          config:
            max-prefixes: 2000
    apply-policy:
      config:
        default-import-policy: accept-route
        import-policy-list:
          - AS65003-IMPORT
        default-export-policy: accept-route
        export-policy-list:
          - AS65003-EXPORT

policy-definitions:
### import policy for AS65001 setting: from

### import policy for AS65001 setting: to
### export policy for AS65001 setting: from

### export policy for AS65001 setting: to
  - name: AS65002-IMPORT
    statements:
    - actions:
        bgp-actions:
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list:
                - ^64686:1101:*$
    - conditions:
        bgp-conditions:
          as-path-length:
            operator: ge
            value: 32
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:5
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set: AS65002-PEER
            match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:7
        route-disposition: reject-route
    - conditions:
        match-prefix-set:
          prefix-set: BOGON
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:3
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set: AS65002-ORIGIN
            match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:10
        route-disposition: reject-route
    - conditions:
        match-prefix-set:
          prefix-set: AS65002-PREFIX
          match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:9
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          rpki-validation-result: invalid
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:13
        route-disposition: reject-route
  - name: AS65002-EXPORT
    statements:
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: NOT-EXPORT-TO-AS65002
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: NOT-EXPORT-TO-AS65002
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: EXPORT-TO-AS65002
      actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: EXPORT-TO-AS65002
      actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: NOT-EXPORT-TO-ALL
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: NOT-EXPORT-TO-ALL
      actions:
        route-disposition: reject-route
    - actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route
  - name: AS65003-IMPORT
    statements:
    - actions:
        bgp-actions:
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list:
                - ^64686:1101:*$
    - conditions:
        bgp-conditions:
          as-path-length:
            operator: ge
            value: 32
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:5
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set: AS65003-PEER
            match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:7
        route-disposition: reject-route
    - conditions:
        match-prefix-set:
          prefix-set: BOGON
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:3
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set: AS65003-ORIGIN
            match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:10
        route-disposition: reject-route
    - conditions:
        match-prefix-set:
          prefix-set: AS65003-PREFIX
          match-set-options: invert
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:9
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          rpki-validation-result: invalid
      actions:
        bgp-actions:
          set-large-community:
            options: add
            set-large-community-method:
              communities-list:
                - 64686:1101:13
        route-disposition: reject-route
  - name: AS65003-EXPORT
    statements:
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: NOT-EXPORT-TO-AS65003
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: NOT-EXPORT-TO-AS65003
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: EXPORT-TO-AS65003
      actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: EXPORT-TO-AS65003
      actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set: NOT-EXPORT-TO-ALL
      actions:
        route-disposition: reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set: NOT-EXPORT-TO-ALL
      actions:
        route-disposition: reject-route
    - actions:
        bgp-actions:
          set-community:
            options: remove
            set-community-method:
              communities-list: ^(0|64686):[0-9]+$
          set-large-community:
            options: remove
            set-large-community-method:
              communities-list: ^64686:[0-9]+:[0-9]+$
        route-disposition: accept-route

defined-sets:
  prefix-sets:
### prefix list for AS65001 setting: from

### prefix list for AS65001 setting: to
    - prefix-set-name: AS65002-PREFIX
      prefix-list:
        - ip-prefix: 10.2.0.0/16
        - ip-prefix: 10.22.0.0/16
    - prefix-set-name: AS65003-PREFIX
      prefix-list:
        - ip-prefix: 10.3.0.0/16
    - prefix-set-name: BOGON
      prefix-list:
        - ip-prefix: 0.0.0.0/8
          masklength-range: 8..32
        ## commendout for demo
        #- ip-prefix: 10.0.0.0/8
        #  masklength-range: 8..32
        - ip-prefix: 127.0.0.0/8
          masklength-range: 8..32
        - ip-prefix: 169.254.0.0/16
          masklength-range: 16..32
        - ip-prefix: 172.16.0.0/12
          masklength-range: 12..32
        - ip-prefix: 192.0.0.0/24
          masklength-range: 24..32
        - ip-prefix: 192.0.2.0/24
          masklength-range: 24..32
        - ip-prefix: 192.168.0.0/16
          masklength-range: 16..32
        - ip-prefix: 198.18.0.0/15
          masklength-range: 15..32
        - ip-prefix: 198.51.100.0/24
          masklength-range: 24..32
        - ip-prefix: 203.0.113.0/24
          masklength-range: 24..32
        - ip-prefix: 224.0.0.0/3
          masklength-range: 3..32
        - ip-prefix: 240.0.0.0/4
          masklength-range: 4..32
        - ip-prefix: 255.255.255.255/32
          masklength-range: 32..32
  bgp-defined-sets:
    as-path-sets:
### as path list for AS65001 setting: from

### as path list for AS65001 setting: to
      - as-path-set-name: AS65002-PEER
        as-path-list:
          - ^65002_
      - as-path-set-name: AS65002-ORIGIN
        as-path-list:
          - _65002$
      - as-path-set-name: AS65003-PEER
        as-path-list:
          - ^65003_
      - as-path-set-name: AS65003-ORIGIN
        as-path-list:
          - _65003$
    community-sets:
### community list for AS65001 setting: from

### community list for AS65001 setting: to
      - community-set-name: NOT-EXPORT-TO-AS65002
        community-list:
          - 0:65002
      - community-set-name: EXPORT-TO-AS65002
        community-list:
          - 64686:65002
      - community-set-name: NOT-EXPORT-TO-AS65003
        community-list:
          - 0:65003
      - community-set-name: EXPORT-TO-AS65003
        community-list:
          - 64686:65003
      - community-set-name: NOT-EXPORT-TO-ALL
        community-list:
          - 0:64686
    large-community-sets:
### large community list for AS65001 setting: from

### large community list for AS65001 setting: to
      - large-community-set-name: NOT-EXPORT-TO-AS65002
        large-community-list:
          - 64686:0:65002
      - large-community-set-name: EXPORT-TO-AS65002
        large-community-list:
          - 64686:1:65002
      - large-community-set-name: NOT-EXPORT-TO-AS65003
        large-community-list:
          - 64686:0:65003
      - large-community-set-name: EXPORT-TO-AS65003
        large-community-list:
          - 64686:1:65003
      - large-community-set-name: NOT-EXPORT-TO-ALL
        large-community-list:
          - 64686:0:0
