global:
  config:
    as:                           64686
    router-id:                    10.173.176.211

mrt-dump:
  - config:
      dump-type:                  updates
      file-name:                  /tmp/updates.2006-01-02_1504.mrt
      rotation-interval:          180

neighbors:
  - config:
      neighbor-address:           10.173.176.101
      peer-as:                    65001
      auth-password:              pass65001
      admin-down: false
    timers:
      config:
        hold-time:                90
        keepalive-interval:       30
    transport:
      config:
        passive-mode:             true
    route-server:
      config:
        route-server-client:      true
    afi-safis:
      - config:
          afi-safi-name:          ipv4-unicast
        prefix-limit:
          config:
            max-prefixes:         2000
    apply-policy:
      config:
        import-policy-list:       [AS65001-IMPORT]
        default-import-policy:    reject-route
        export-policy-list:       [AS65001-EXPORT]
        default-export-policy:    accept-route
  - config:
      neighbor-address:           10.173.176.102
      peer-as:                    65002
      auth-password:              pass65002
      admin-down: false
    timers:
      config:
        hold-time:                90
        keepalive-interval:       30
    transport:
      config:
        passive-mode:             true
    route-server:
      config:
        route-server-client:      true
    afi-safis:
      - config:
          afi-safi-name:          ipv4-unicast
        prefix-limit:
          config:
            max-prefixes:         2000
    apply-policy:
      config:
        import-policy-list:       [AS65002-IMPORT]
        default-import-policy:    reject-route
        export-policy-list:       [AS65002-EXPORT]
        default-export-policy:    accept-route
policy-definitions:
  - name:                         AS65001-IMPORT
    statements:
    - conditions:
        match-prefix-set:
          prefix-set:             MARTIAN
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          as-path-length:
            operator:             ge
            value:                256
      actions:
        route-disposition:        reject-route
    - conditions:
        match-prefix-set:
          prefix-set:             IX-PREFIX
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set:          AS65001
            match-set-options:    invert
      actions:
        route-disposition:        reject-route
    - conditions:
        match-prefix-set:
          prefix-set:             AS65001-PREFIX
        bgp-conditions:
          match-as-path-set:
            as-path-set:          AS65001-PATH
      actions:
        route-disposition:        accept-route
  - name:                         AS65001-EXPORT
    statements:
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        NOT-EXPORT-TO-AS65001
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set:  NOT-EXPORT-TO-AS65001
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        EXPORT-TO-AS65001
      actions:
        bgp-actions:
          set-community:
            options:              remove
            set-community-method:
              communities-list:   ["^(0|64686):[0-9]+"]
        route-disposition:        accept-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set:  EXPORT-TO-AS65001
      actions:
        bgp-actions:
          set-community:
            options:              remove
            set-community-method:
              communities-list:   ["^(0|64686):[0-9]+:[0-9]+"]
        route-disposition:        accept-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        NOT-EXPORT-TO-ALL
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-large-community-set:
            large-community-set:  NOT-EXPORT-TO-ALL
      actions:
        route-disposition:        reject-route
  - name:                         AS65002-IMPORT
    statements:
    - conditions:
        match-prefix-set:
          prefix-set:             MARTIAN
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          as-path-length:
            operator:             ge
            value:                256
      actions:
        route-disposition:        reject-route
    - conditions:
        match-prefix-set:
          prefix-set:             IX-PREFIX
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-as-path-set:
            as-path-set:          AS65002
            match-set-options:    invert
      actions:
        route-disposition:        reject-route
    - conditions:
        match-prefix-set:
          prefix-set:             AS65002-PREFIX
        bgp-conditions:
          match-as-path-set:
            as-path-set:          AS65002-PATH
      actions:
        route-disposition:        accept-route
  - name:                         AS65002-EXPORT
    statements:
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        NOT-EXPORT-TO-AS65002
      actions:
        route-disposition:        reject-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        EXPORT-TO-AS65002
      actions:
        bgp-actions:
          set-community:
            options:              remove
            set-community-method:
              communities-list:   ["^(0|64686):[0-9]+"]
        route-disposition:        accept-route
    - conditions:
        bgp-conditions:
          match-community-set:
            community-set:        NOT-EXPORT-TO-ALL
      actions:
        route-disposition:        reject-route
    - actions:
        bgp-actions:
          set-community:
            options:              remove
            set-community-method:
              communities-list:   ["^(0|64686):[0-9]+"]
        route-disposition:        accept-route

defined-sets:
  prefix-sets:
    - prefix-set-name:            MARTIAN
      prefix-list:
        - ip-prefix:              0.0.0.0/8
          masklength-range:       8..32
#        - ip-prefix:              10.0.0.0/8
#          masklength-range:       8..32
        - ip-prefix:              127.0.0.0/8
          masklength-range:       8..32
        - ip-prefix:              169.254.0.0/16
          masklength-range:       16..32
        - ip-prefix:              172.16.0.0/12
          masklength-range:       12..32
        - ip-prefix:              192.0.0.0/24
          masklength-range:       24..32
        - ip-prefix:              192.0.2.0/24
          masklength-range:       24..32
        - ip-prefix:              192.168.0.0/16
          masklength-range:       16..32
        - ip-prefix:              198.18.0.0/15
          masklength-range:       15..32
        - ip-prefix:              198.51.100.0/24
          masklength-range:       24..32
        - ip-prefix:              203.0.113.0/24
          masklength-range:       24..32
        - ip-prefix:              224.0.0.0/3
          masklength-range:       3..32
        - ip-prefix:              240.0.0.0/4
          masklength-range:       4..32
        - ip-prefix:              255.255.255.255/32
          masklength-range:       32..32
    - prefix-set-name:            IX-PREFIX
      prefix-list:
        - ip-prefix:              10.173.176.0/24
          masklength-range:       24..32
    - prefix-set-name:            AS65001-PREFIX
      prefix-list:
        - ip-prefix:              10.1.0.0/16
    - prefix-set-name:            AS65002-PREFIX
      prefix-list:
        - ip-prefix:              10.2.0.0/16
  bgp-defined-sets:
    community-sets:
      - community-set-name:       NOT-EXPORT-TO-ALL
        community-list:
          - 0:64686
      - community-set-name:       NOT-EXPORT-TO-AS65001
        community-list:
          - 0:65001
      - community-set-name:       EXPORT-TO-AS65001
        community-list:
          - 64686:65001
      - community-set-name:       NOT-EXPORT-TO-AS65002
        community-list:
          - 0:65002
      - community-set-name:       EXPORT-TO-AS65002
        community-list:
          - 64686:65002
    large-community-sets:
      - large-community-set-name: NOT-EXPORT-TO-ALL
        large-community-list:
          - 64686:0:0
      - large-community-set-name: NOT-EXPORT-TO-AS65001
        large-community-list:
          - 64686:0:65001
      - large-community-set-name: EXPORT-TO-AS65001
        large-community-list:
          - 64686:1:65001
      - large-community-set-name: NOT-EXPORT-TO-AS65002
        large-community-list:
          - 64686:0:65002
      - large-community-set-name: EXPORT-TO-AS65002
        large-community-list:
          - 64686:1:65002
    as-path-sets:
      - as-path-set-name:         AS65001
        as-path-list:
          - ^65001_
      - as-path-set-name:         AS65001-PATH
        as-path-list:
          - _65001$
      - as-path-set-name:         AS65002
        as-path-list:
          - ^65002_
      - as-path-set-name:         AS65002-PATH
        as-path-list:
          - _65002$
